#r "nuget: Microsoft.DeepDev.TokenizerLib"
#r "nuget: Azure.Search.Documents"
#r "nuget: Microsoft.SemanticKernel" 
#r "nuget: FSharp.SystemTextJson"
#r "nuget: FSharp.Data"
#r "nuget: FSharp.Collections.ParallelSeq"
#r "nuget: FSharp.Control.AsyncSeq"
#r "nuget: FsPickler.Json"
#r "nuget: PdfPig, *-*"
//#r "nuget: DocumentFormat.OpenXml"
#r "nuget: Plotly.NET"
#r "nuget: Azure.Identity"
#r "nuget: azure.security.keyvault.secrets"
#r "nuget: Microsoft.Extensions.Hosting"
#r "nuget: Microsoft.Extensions.Logging"
#r "nuget: Microsoft.Z3"
#r "nuget: FsExcel"
#r "nuget: Microsoft.Data.Analysis"
#r "nuget: Microsoft.ML"
#r "nuget: System.Data.Odbc, 9.0.0-preview.2.24128.5"


#load "../Settings.fs"
#load "../HiveUtils.fs"
#load "../GenUtils.fs"
#load "../SemanticVectorSearch.fs"
