#r "nuget: Microsoft.DeepDev.TokenizerLib"
#r "nuget: Azure.Search.Documents"
#r "nuget: Microsoft.SemanticKernel" 
#r "nuget: FSharp.SystemTextJson"
#r "nuget: FSharp.Data"
#r "nuget: FSharp.Collections.ParallelSeq"
#r "nuget: FSharp.Control.AsyncSeq"
#r "nuget: FsPickler.Json"
#r "nuget: PdfPig, *-*"
#r "nuget: DocumentFormat.OpenXml"
#r "nuget: Plotly.NET"
#r "nuget: Azure.Identity"
#r "nuget: azure.security.keyvault.secrets"
#r "nuget: Microsoft.Extensions.Hosting"
#r "nuget: Microsoft.Extensions.Logging"
#r "nuget: Microsoft.Z3"

#load "../Settings.fs"
#load "../GenUtils.fs"
#load "../SemanticVectorSearch.fs"
